// flow-typed signature: 6d416e015f8393349cedcb0a3107a9b4
// flow-typed version: <<STUB>>/roboto-fontface_v^0.6.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'roboto-fontface'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'roboto-fontface' {
  declare module.exports: any;
}
